platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpbackup
- name: gpbackup_1.12.1_dependencies
- name: gpdb_src
- name: bin_gpdb

params:
  GPBACKUP_VERSION:

run:
  path: gpbackup/ci/scripts/integration-tests-fixed-version.bash
